name: e2etest-Test_ProjectRepoNoBrev

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  BREV_SETUP_TEST_CMD_DIR: /home/brev/workspace/actions-runner/_work/brev-cli/brev-cli

jobs:
  Test_ProjectRepoNoBrev:

    runs-on: [self-hosted]
    if: "contains(github.event.head_commit.message, 'e2etest')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true      - name: expire test cache
        run: go clean -testcache
      - name: test
        run: go test -timeout 240s -run ^Test_ProjectRepoNoBrev$ github.com/brevdev/brev-cli/e2etest/setup

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
