name: e2etest-Test_UserBrevProjectBrevV1All

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  BREV_SETUP_TEST_CMD_DIR: /home/brev/workspace/actions-runner/_work/brev-cli/brev-cli

jobs:
  Test_UserBrevProjectBrevV1All:

    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: expire test cache
        run: go clean -testcache
      - name: test
        run: go test -timeout 240s -run ^Test_UserBrevProjectBrevV1All$ github.com/brevdev/brev-cli/e2etest/setup

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
